In [2]:
import pandas as pd
data=[]
for i in range(11,22):
    df=pd.read_csv(f'historical_weather_315_data20{i}.csv')
   
    df['date'] = pd.to_datetime(df['date'])  # Convert to datetime format
    
    # Add year and month columns
    df['year'] = df['date'].dt.year
    df['month'] = df['date'].dt.month
    
    # Group by state, district, year, and month, and aggregate numerical columns
    monthly_df = df.groupby(['state', 'district', 'year', 'month']).agg({
        'precipitation_sum': 'mean',
        'relative_humidity_2m_mean': 'mean',  # or 'sum' if needed
        'latitude': 'first',
        'longitude': 'first', 
        'temperature_2m_mean':'mean', 
        'wind_speed_10m_mean':'mean'
    }).reset_index()
    data.append(monthly_df)

In [3]:
len(data)

11

In [4]:
data_1=[]
for i in range(11,22):
    
    df=pd.read_csv(f'historical_weather_635_data20{i}.csv')
    
        
    df['date'] = pd.to_datetime(df['date'])  # Convert to datetime format
    
    # Add year and month columns
    df['year'] = df['date'].dt.year
    df['month'] = df['date'].dt.month
    
    # Group by state, district, year, and month, and aggregate numerical columns
    monthly_df = df.groupby(['state', 'district', 'year', 'month']).agg({
        'precipitation_sum': 'mean',
        'relative_humidity_2m_mean': 'mean',  # or 'sum' if needed
        'latitude': 'first',
        'longitude': 'first', 
        'temperature_2m_mean':'mean', 
        'wind_speed_10m_mean':'mean'
    }).reset_index()
    data_1.append(monthly_df)

In [5]:
data_1

[             state        district  year  month  precipitation_sum  \
 0     Chhattisgarh           Balod  2011      1           0.000000
 1     Chhattisgarh           Balod  2011      2           0.646429
 2     Chhattisgarh           Balod  2011      3           0.045161
 3     Chhattisgarh           Balod  2011      4           1.390000
 4     Chhattisgarh           Balod  2011      5           0.054839
 ...            ...             ...   ...    ...                ...
 3283   West Bengal  Uttar Dinajpur  2011      8          12.903226
 3284   West Bengal  Uttar Dinajpur  2011      9           9.546667
 3285   West Bengal  Uttar Dinajpur  2011     10           1.022581
 3286   West Bengal  Uttar Dinajpur  2011     11           0.120000
 3287   West Bengal  Uttar Dinajpur  2011     12           0.041935

       relative_humidity_2m_mean   latitude  longitude  temperature_2m_mean  \
 0                     51.000000  20.727719  81.144695            19.890323
 1                     49.750000  20.727719  81.144695            23.475000
 2                     32.741935  20.727719  81.144695            28.806452
 3                     45.800000  20.727719  81.144695            30.356667
 4                     33.129032  20.727719  81.144695            34.561290
 ...                         ...        ...        ...                  ...
 3283                  87.129032  25.872143  87.961986            27.448387
 3284                  86.466667  25.872143  87.961986            27.250000
 3285                  79.870968  25.872143  87.961986            26.003226
 3286                  71.433333  25.872143  87.961986            21.486667
 3287                  71.258065  25.872143  87.961986            18.732258

       wind_speed_10m_mean
 0                6.800000
 1                7.253571
 2                8.793548
 3                7.950000
 4                9.890323
 ...                   ...
 3283            10.529032
 3284             9.353333
 3285             4.919355
 3286             6.293333
 3287             5.696774

 [3288 rows x 10 columns],
                   state        district  year  month  precipitation_sum  \
 0     Arunachal Pradesh          Namsai  2012      1           1.912903
 1     Arunachal Pradesh          Namsai  2012      2           0.937931
 2     Arunachal Pradesh          Namsai  2012      3           3.174194
 3     Arunachal Pradesh          Namsai  2012      4          10.250000
 4     Arunachal Pradesh          Namsai  2012      5           2.632258
 ...                 ...             ...   ...    ...                ...
 3823        West Bengal  Uttar Dinajpur  2012      8           7.693548
 3824        West Bengal  Uttar Dinajpur  2012      9           9.876667
 3825        West Bengal  Uttar Dinajpur  2012     10           2.122581
 3826        West Bengal  Uttar Dinajpur  2012     11           0.003333
 3827        West Bengal  Uttar Dinajpur  2012     12           0.000000

       relative_humidity_2m_mean   latitude  longitude  temperature_2m_mean  \
 0                     82.387097  27.714031  96.015971            14.587097
 1                     76.655172  27.714031  96.015971            17.551724
 2                     72.322581  27.714031  96.015971            19.790323
 3                     81.033333  27.714031  96.015971            21.780000
 4                     78.870968  27.714031  96.015971            25.958065
 ...                         ...        ...        ...                  ...
 3823                  85.387097  25.872143  87.961986            28.045161
 3824                  87.066667  25.872143  87.961986            27.163333
 3825                  79.548387  25.872143  87.961986            24.838710
 3826                  64.000000  25.872143  87.961986            21.140000
 3827                  70.354839  25.872143  87.961986            18.177419

       wind_speed_10m_mean
 0                2.909677
 1                3.275862
 2                3.867742
 3                3.990000
 4                3.490323
 ...                   ...
 3823             8.587097
 3824             8.466667
 3825             5.519355
 3826             6.306667
 3827             6.016129

 [3828 rows x 10 columns],
                   state        district  year  month  precipitation_sum  \
 0     Arunachal Pradesh          Namsai  2013      1           0.396774
 1     Arunachal Pradesh          Namsai  2013      2           0.382143
 2     Arunachal Pradesh          Namsai  2013      3           4.787097
 3     Arunachal Pradesh          Namsai  2013      4           7.950000
 4     Arunachal Pradesh          Namsai  2013      5           8.461290
 ...                 ...             ...   ...    ...                ...
 3823        West Bengal  Uttar Dinajpur  2013      8           8.270968
 3824        West Bengal  Uttar Dinajpur  2013      9           5.713333
 3825        West Bengal  Uttar Dinajpur  2013     10           7.387097
 3826        West Bengal  Uttar Dinajpur  2013     11           0.046667
 3827        West Bengal  Uttar Dinajpur  2013     12           0.006452

       relative_humidity_2m_mean   latitude  longitude  temperature_2m_mean  \
 0                     76.903226  27.714031  96.015971            14.816129
 1                     65.785714  27.714031  96.015971            19.021429
 2                     62.354839  27.714031  96.015971            21.712903
 3                     79.900000  27.714031  96.015971            22.403333
 4                     84.645161  27.714031  96.015971            24.393548
 ...                         ...        ...        ...                  ...
 3823                  86.806452  25.872143  87.961986            27.406452
 3824                  84.200000  25.872143  87.961986            27.763333
 3825                  84.064516  25.872143  87.961986            24.945161
 3826                  72.700000  25.872143  87.961986            20.653333
 3827                  69.032258  25.872143  87.961986            18.022581

       wind_speed_10m_mean
 0                3.164516
 1                3.575000
 2                3.906452
 3                3.446667
 4                3.390323
 ...                   ...
 3823             9.632258
 3824             7.140000
 3825             7.322581
 3826             6.386667
 3827             6.503226

 [3828 rows x 10 columns],
                   state        district  year  month  precipitation_sum  \
 0     Arunachal Pradesh          Namsai  2014      1           0.232258
 1     Arunachal Pradesh          Namsai  2014      2           1.328571
 2     Arunachal Pradesh          Namsai  2014      3           2.038710
 3     Arunachal Pradesh          Namsai  2014      4           1.316667
 4     Arunachal Pradesh          Namsai  2014      5           6.551613
 ...                 ...             ...   ...    ...                ...
 3823        West Bengal  Uttar Dinajpur  2014      8          15.751613
 3824        West Bengal  Uttar Dinajpur  2014      9          11.463333
 3825        West Bengal  Uttar Dinajpur  2014     10           1.451613
 3826        West Bengal  Uttar Dinajpur  2014     11           0.000000
 3827        West Bengal  Uttar Dinajpur  2014     12           0.025806

       relative_humidity_2m_mean   latitude  longitude  temperature_2m_mean  \
 0                     79.290323  27.714031  96.015971            15.496774
 1                     77.000000  27.714031  96.015971            16.785714
 2                     65.000000  27.714031  96.015971            21.022581
 3                     68.033333  27.714031  96.015971            23.890000
 4                     78.193548  27.714031  96.015971            25.332258
 ...                         ...        ...        ...                  ...
 3823                  87.677419  25.872143  87.961986            27.577419
 3824                  87.100000  25.872143  87.961986            26.923333
 3825                  80.258065  25.872143  87.961986            25.535484
 3826                  68.133333  25.872143  87.961986            22.256667
 3827                  74.032258  25.872143  87.961986            18.448387

       wind_speed_10m_mean
 0                2.964516
 1                3.264286
 2                3.729032
 3                3.573333
 4                3.841935
 ...                   ...
 3823             8.167742
 3824             7.946667
 3825             5.051613
 3826             5.506667
 3827             6.454839

 [3828 rows x 10 columns],
                   state        district  year  month  precipitation_sum  \
 0     Arunachal Pradesh          Namsai  2015      1           1.893548
 1     Arunachal Pradesh          Namsai  2015      2           2.053571
 2     Arunachal Pradesh          Namsai  2015      3           1.612903
 3     Arunachal Pradesh          Namsai  2015      4           8.516667
 4     Arunachal Pradesh          Namsai  2015      5           5.022581
 ...                 ...             ...   ...    ...                ...
 3823        West Bengal  Uttar Dinajpur  2015      8          16.793548
 3824        West Bengal  Uttar Dinajpur  2015      9           5.130000
 3825        West Bengal  Uttar Dinajpur  2015     10           0.864516
 3826        West Bengal  Uttar Dinajpur  2015     11           0.080000
 3827        West Bengal  Uttar Dinajpur  2015     12           0.077419

       relative_humidity_2m_mean   latitude  longitude  temperature_2m_mean  \
 0                     78.161290  27.714031  96.015971            16.080645
 1                     74.428571  27.714031  96.015971            17.528571
 2                     70.193548  27.714031  96.015971            21.467742
 3                     82.033333  27.714031  96.015971            22.120000
 4                     84.548387  27.714031  96.015971            24.838710
 ...                         ...        ...        ...                  ...
 3823                  88.580645  25.872143  87.961986            27.400000
 3824                  85.800000  25.872143  87.961986            27.570000
 3825                  78.419355  25.872143  87.961986            26.135484
 3826                  71.466667  25.872143  87.961986            23.010000
 3827                  69.838710  25.872143  87.961986            18.287097

       wind_speed_10m_mean
 0                3.377419
 1                3.464286
 2                3.609677
 3                3.280000
 4                2.974194
 ...                   ...
 3823             8.329032
 3824             7.116667
 3825             5.574194
 3826             4.966667
 3827             5.829032

 [3828 rows x 10 columns],
                   state        district  year  month  precipitation_sum  \
 0     Arunachal Pradesh          Namsai  2016      1           0.619355
 1     Arunachal Pradesh          Namsai  2016      2           2.148276
 2     Arunachal Pradesh          Namsai  2016      3           4.519355
 3     Arunachal Pradesh          Namsai  2016      4          25.436667
 4     Arunachal Pradesh          Namsai  2016      5           9.500000
 ...                 ...             ...   ...    ...                ...
 3799        West Bengal  Uttar Dinajpur  2016      8           6.522581
 3800        West Bengal  Uttar Dinajpur  2016      9          14.760000
 3801        West Bengal  Uttar Dinajpur  2016     10           3.958065
 3802        West Bengal  Uttar Dinajpur  2016     11           0.006667
 3803        West Bengal  Uttar Dinajpur  2016     12           0.087097

       relative_humidity_2m_mean   latitude  longitude  temperature_2m_mean  \
 0                     78.935484  27.714031  96.015971            14.493548
 1                     77.103448  27.714031  96.015971            17.782759
 2                     77.193548  27.714031  96.015971            20.319355
 3                     87.333333  27.714031  96.015971            21.633333
 4                     85.064516  27.714031  96.015971            24.654839
 ...                         ...        ...        ...                  ...
 3799                  82.612903  25.872143  87.961986            28.738710
 3800                  89.200000  25.872143  87.961986            27.040000
 3801                  81.451613  25.872143  87.961986            26.035484
 3802                  68.366667  25.872143  87.961986            22.630000
 3803                  74.451613  25.872143  87.961986            19.493548

       wind_speed_10m_mean
 0                3.106452
 1                3.555172
 2                3.300000
 3                3.883333
 4                3.067742
 ...                   ...
 3799            10.280645
 3800             6.823333
 3801             5.358065
 3802             5.533333
 3803             6.280645

 [3804 rows x 10 columns],
                   state        district  year  month  precipitation_sum  \
 0     Arunachal Pradesh          Namsai  2017      1           0.912903
 1     Arunachal Pradesh          Namsai  2017      2           3.985714
 2     Arunachal Pradesh          Namsai  2017      3           9.045161
 3     Arunachal Pradesh          Namsai  2017      4          15.593333
 4     Arunachal Pradesh          Namsai  2017      5          12.083871
 ...                 ...             ...   ...    ...                ...
 3823        West Bengal  Uttar Dinajpur  2017      8          15.225806
 3824        West Bengal  Uttar Dinajpur  2017      9           7.140000
 3825        West Bengal  Uttar Dinajpur  2017     10           3.106452
 3826        West Bengal  Uttar Dinajpur  2017     11           0.016667
 3827        West Bengal  Uttar Dinajpur  2017     12           0.041935

       relative_humidity_2m_mean   latitude  longitude  temperature_2m_mean  \
 0                     71.161290  27.714031  96.015971            17.390323
 1                     71.964286  27.714031  96.015971            18.925000
 2                     78.903226  27.714031  96.015971            19.322581
 3                     82.000000  27.714031  96.015971            22.323333
 4                     83.838710  27.714031  96.015971            24.670968
 ...                         ...        ...        ...                  ...
 3823                  87.064516  25.872143  87.961986            27.996774
 3824                  86.933333  25.872143  87.961986            27.836667
 3825                  84.903226  25.872143  87.961986            25.877419
 3826                  72.966667  25.872143  87.961986            21.906667
 3827                  74.903226  25.872143  87.961986            19.448387

       wind_speed_10m_mean
 0                5.361290
 1                5.192857
 2                5.845161
 3                6.103333
 4                5.167742
 ...                   ...
 3823             7.729032
 3824             6.966667
 3825             7.641935
 3826             6.790000
 3827             6.545161

 [3828 rows x 10 columns],
                   state        district  year  month  precipitation_sum  \
 0     Arunachal Pradesh          Namsai  2018      1           2.703226
 1     Arunachal Pradesh          Namsai  2018      2           2.885714
 2     Arunachal Pradesh          Namsai  2018      3           4.912903
 3     Arunachal Pradesh          Namsai  2018      4           6.926667
 4     Arunachal Pradesh          Namsai  2018      5           9.116129
 ...                 ...             ...   ...    ...                ...
 3823        West Bengal  Uttar Dinajpur  2018      8           9.861290
 3824        West Bengal  Uttar Dinajpur  2018      9           5.393333
 3825        West Bengal  Uttar Dinajpur  2018     10           0.941935
 3826        West Bengal  Uttar Dinajpur  2018     11           0.050000
 3827        West Bengal  Uttar Dinajpur  2018     12           0.616129

       relative_humidity_2m_mean   latitude  longitude  temperature_2m_mean  \
 0                     78.000000  27.714031  96.015971            16.451613
 1                     79.142857  27.714031  96.015971            17.771429
 2                     77.290323  27.714031  96.015971            20.412903
 3                     79.833333  27.714031  96.015971            22.956667
 4                     86.580645  27.714031  96.015971            24.183871
 ...                         ...        ...        ...                  ...
 3823                  85.580645  25.872143  87.961986            28.529032
 3824                  84.400000  25.872143  87.961986            28.186667
 3825                  77.354839  25.872143  87.961986            25.345161
 3826                  67.800000  25.872143  87.961986            22.250000
 3827                  70.483871  25.872143  87.961986            17.383871

       wind_speed_10m_mean
 0                4.887097
 1                4.792857
 2                5.609677
 3                4.640000
 4                4.587097
 ...                   ...
 3823             9.854839
 3824             8.203333
 3825             7.090323
 3826             5.990000
 3827             7.170968

 [3828 rows x 10 columns],
                   state        district  year  month  precipitation_sum  \
 0     Arunachal Pradesh          Namsai  2019      1           1.245161
 1     Arunachal Pradesh          Namsai  2019      2           5.178571
 2     Arunachal Pradesh          Namsai  2019      3           4.174194
 3     Arunachal Pradesh          Namsai  2019      4           9.996667
 4     Arunachal Pradesh          Namsai  2019      5          12.874194
 ...                 ...             ...   ...    ...                ...
 3823        West Bengal  Uttar Dinajpur  2019      8           8.609677
 3824        West Bengal  Uttar Dinajpur  2019      9          17.350000
 3825        West Bengal  Uttar Dinajpur  2019     10           2.441935
 3826        West Bengal  Uttar Dinajpur  2019     11           0.013333
 3827        West Bengal  Uttar Dinajpur  2019     12           0.103226

       relative_humidity_2m_mean   latitude  longitude  temperature_2m_mean  \
 0                     68.451613  27.714031  96.015971            16.903226
 1                     76.750000  27.714031  96.015971            17.753571
 2                     76.935484  27.714031  96.015971            19.622581
 3                     82.300000  27.714031  96.015971            23.113333
 4                     86.870968  27.714031  96.015971            24.009677
 ...                         ...        ...        ...                  ...
 3823                  84.548387  25.872143  87.961986            28.893548
 3824                  88.566667  25.872143  87.961986            27.126667
 3825                  84.612903  25.872143  87.961986            25.112903
 3826                  72.200000  25.872143  87.961986            23.460000
 3827                  74.225806  25.872143  87.961986            16.793548

       wind_speed_10m_mean
 0                5.325806
 1                5.485714
 2                5.561290
 3                4.606667
 4                4.967742
 ...                   ...
 3823            10.135484
 3824            10.033333
 3825             6.222581
 3826             6.166667
 3827             7.432258

 [3828 rows x 10 columns],
                   state        district  year  month  precipitation_sum  \
 0     Arunachal Pradesh          Namsai  2020      1           3.732258
 1     Arunachal Pradesh          Namsai  2020      2           2.500000
 2     Arunachal Pradesh          Namsai  2020      3           3.441935
 3     Arunachal Pradesh          Namsai  2020      4           6.613333
 4     Arunachal Pradesh          Namsai  2020      5          15.741935
 ...                 ...             ...   ...    ...                ...
 3823        West Bengal  Uttar Dinajpur  2020      8           9.738710
 3824        West Bengal  Uttar Dinajpur  2020      9          16.850000

In [6]:
len(data_1)

11

In [7]:
combined_df_1 = pd.concat(data, ignore_index=True)

In [8]:
combined_df_1

,state,district,year,month,precipitation_sum,relative_humidity_2m_mean,latitude,longitude,temperature_2m_mean,wind_speed_10m_mean
0,Andhra Pradesh,Anantapur,2011,1,0.022581,50.258065,14.72422,77.430674,23.990323,10.270968
1,Andhra Pradesh,Anantapur,2011,2,0.014286,42.892857,14.72422,77.430674,25.900000,10.132143
2,Andhra Pradesh,Anantapur,2011,3,0.000000,31.451613,14.72422,77.430674,29.861290,10.403226
3,Andhra Pradesh,Anantapur,2011,4,1.046667,45.733333,14.72422,77.430674,30.550000,9.220000
4,Andhra Pradesh,Anantapur,2011,5,1.480645,52.387097,14.72422,77.430674,30.845161,13.180645
...,...,...,...,...,...,...,...,...,...,...
41659,The Dadra And Nagar Haveli And Daman And Diu,Surguja,2021,8,8.900000,87.290323,22.89624,83.096310,24.412903,8.854839
41660,The Dadra And Nagar Haveli And Daman And Diu,Surguja,2021,9,9.083333,86.933333,22.89624,83.096310,24.006667,8.813333
41661,The Dadra And Nagar Haveli And Daman And Diu,Surguja,2021,10,1.467742,72.677419,22.89624,83.096310,22.890323,7.167742
41662,The Dadra And Nagar Haveli And Daman And Diu,Surguja,2021,11,0.280000,63.200000,22.89624,83.096310,19.880000,6.480000
41663,The Dadra And Nagar Haveli And Daman And Diu,Surguja,2021,12,0.445161,61.645161,22.89624,83.096310,16.509677,7.864516

In [9]:
combined_df_2 = pd.concat(data_1, ignore_index=True)

In [10]:
combined_df_2

,state,district,year,month,precipitation_sum,relative_humidity_2m_mean,latitude,longitude,temperature_2m_mean,wind_speed_10m_mean
0,Chhattisgarh,Balod,2011,1,0.000000,51.000000,20.727719,81.144695,19.890323,6.800000
1,Chhattisgarh,Balod,2011,2,0.646429,49.750000,20.727719,81.144695,23.475000,7.253571
2,Chhattisgarh,Balod,2011,3,0.045161,32.741935,20.727719,81.144695,28.806452,8.793548
3,Chhattisgarh,Balod,2011,4,1.390000,45.800000,20.727719,81.144695,30.356667,7.950000
4,Chhattisgarh,Balod,2011,5,0.054839,33.129032,20.727719,81.144695,34.561290,9.890323
...,...,...,...,...,...,...,...,...,...,...
41539,West Bengal,Uttar Dinajpur,2021,8,13.629032,89.225806,25.872143,87.961986,27.841935,7.877419
41540,West Bengal,Uttar Dinajpur,2021,9,5.193333,84.633333,25.872143,87.961986,28.236667,8.743333
41541,West Bengal,Uttar Dinajpur,2021,10,8.635484,82.064516,25.872143,87.961986,26.464516,7.503226
41542,West Bengal,Uttar Dinajpur,2021,11,0.000000,74.900000,25.872143,87.961986,20.900000,6.253333
41543,West Bengal,Uttar Dinajpur,2021,12,0.258065,73.193548,25.872143,87.961986,18.174194,7.283871

In [11]:
f = pd.concat([combined_df_1,combined_df_2], ignore_index=True)

In [12]:
f

,state,district,year,month,precipitation_sum,relative_humidity_2m_mean,latitude,longitude,temperature_2m_mean,wind_speed_10m_mean
0,Andhra Pradesh,Anantapur,2011,1,0.022581,50.258065,14.724220,77.430674,23.990323,10.270968
1,Andhra Pradesh,Anantapur,2011,2,0.014286,42.892857,14.724220,77.430674,25.900000,10.132143
2,Andhra Pradesh,Anantapur,2011,3,0.000000,31.451613,14.724220,77.430674,29.861290,10.403226
3,Andhra Pradesh,Anantapur,2011,4,1.046667,45.733333,14.724220,77.430674,30.550000,9.220000
4,Andhra Pradesh,Anantapur,2011,5,1.480645,52.387097,14.724220,77.430674,30.845161,13.180645
...,...,...,...,...,...,...,...,...,...,...
83203,West Bengal,Uttar Dinajpur,2021,8,13.629032,89.225806,25.872143,87.961986,27.841935,7.877419
83204,West Bengal,Uttar Dinajpur,2021,9,5.193333,84.633333,25.872143,87.961986,28.236667,8.743333
83205,West Bengal,Uttar Dinajpur,2021,10,8.635484,82.064516,25.872143,87.961986,26.464516,7.503226
83206,West Bengal,Uttar Dinajpur,2021,11,0.000000,74.900000,25.872143,87.961986,20.900000,6.253333
83207,West Bengal,Uttar Dinajpur,2021,12,0.258065,73.193548,25.872143,87.961986,18.174194,7.283871

In [13]:
f.isnull().sum()

state                        0
district                     0
year                         0
month                        0
precipitation_sum            0
relative_humidity_2m_mean    0
latitude                     0
longitude                    0
temperature_2m_mean          0
wind_speed_10m_mean          0
dtype: int64

In [17]:
f.to_csv('final_weather.csv',index=False)